import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, test } from "node:test";

import {
  createIssueLease,
  ensureIssueWorktree,
  issueLeaseRef,
  issueWorkspaceIdentity,
  parseIssueLease,
  releaseIssueLease,
  renewIssueLease,
  serializeIssueLease,
  type IssueLease,
  type IssueLeaseAuthority,
} from "../src/coordination/index.ts";

/**
 * Proves that `src/coordination/**` preserves the lease record format and
 * `agent/issue-N` / `.worktrees/issue-N` naming convention byte-for-byte, so
 * leases and worktrees already produced by any pre-existing compatible
 * harness (including Campsty's own `.agents/coordination` copy this module
 * was ported from) remain readable/renewable/releasable/recoverable without
 * a format change. This is a hot swap of the implementation behind an
 * existing production lease system, not a greenfield install (#19).
 */

// A byte-for-byte golden record of the shape the shared coordination module
// has always produced (version 1, one JSON object per line, trailing
// newline). Intentionally hand-written rather than generated by the current
// code, so a future accidental format change is caught here instead of only
// being self-consistent with itself.
const GOLDEN_LEASE_583_RECORD =
  '{"version":1,"issueNumber":583,"branch":"agent/issue-583","worktree":".worktrees/issue-583","agent":"pi-next","runId":"legacy-run","sessionId":"legacy-run-session","acquiredAt":"2026-08-10T09:00:00.000Z","expiresAt":"2026-08-10T09:30:00.000Z"}\n';

class MemoryAuthority implements IssueLeaseAuthority {
  leases = new Map<number, IssueLease>();
  async read(issue: number) {
    return this.leases.get(issue);
  }
  async create(issue: number, lease: IssueLease) {
    if (this.leases.has(issue)) throw new Error("compare-and-swap failed");
    this.leases.set(issue, lease);
  }
  async replace(issue: number, expected: IssueLease, lease: IssueLease) {
    if (this.leases.get(issue) !== expected) throw new Error("compare-and-swap failed");
    this.leases.set(issue, lease);
  }
  async remove(issue: number, expected: IssueLease) {
    if (this.leases.get(issue) !== expected) throw new Error("compare-and-swap failed");
    this.leases.delete(issue);
  }
}

const temporaryDirectories: string[] = [];
afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) rmSync(directory, { recursive: true, force: true });
});

function git(cwd: string, args: string[]): string {
  return execFileSync("git", ["-C", cwd, ...args], { encoding: "utf8" }).trim();
}

describe("lease record format compatibility", () => {
  test("derives the exact expected ref path and workspace identity for a live issue", () => {
    assert.equal(issueLeaseRef(583), "refs/leases/issues/583");
    assert.deepEqual(issueWorkspaceIdentity(583), {
      issueNumber: 583,
      branch: "agent/issue-583",
      worktree: ".worktrees/issue-583",
    });
  });

  test("reads a golden lease record without any format translation", () => {
    const parsed = parseIssueLease(GOLDEN_LEASE_583_RECORD);
    assert.deepEqual(parsed, {
      version: 1,
      issueNumber: 583,
      agent: "pi-next",
      runId: "legacy-run",
      sessionId: "legacy-run-session",
      branch: "agent/issue-583",
      worktree: ".worktrees/issue-583",
      acquiredAt: "2026-08-10T09:00:00.000Z",
      expiresAt: "2026-08-10T09:30:00.000Z",
    });
  });

  test("re-serializes a parsed golden record byte-for-byte, proving no format drift", () => {
    const parsed = parseIssueLease(GOLDEN_LEASE_583_RECORD);
    assert.equal(serializeIssueLease(parsed), GOLDEN_LEASE_583_RECORD);
  });

  test("renews and releases a lease that originated from the golden serialization", async () => {
    const authority = new MemoryAuthority();
    const legacy = parseIssueLease(GOLDEN_LEASE_583_RECORD);
    authority.leases.set(583, legacy);

    const renewed = await renewIssueLease(authority, legacy, new Date("2026-08-10T09:10:00.000Z"));
    assert.equal(renewed.issueNumber, 583);
    assert.equal(renewed.agent, "pi-next");
    assert.equal(renewed.runId, "legacy-run");
    assert.equal(renewed.branch, "agent/issue-583");
    assert.equal(renewed.worktree, ".worktrees/issue-583");

    await releaseIssueLease(authority, renewed);
    assert.equal(await authority.read(583), undefined);
  });

  test("stays consistent for a lease newly minted through the shared module", () => {
    const fresh = createIssueLease({
      issueNumber: 583,
      agent: "pi-next",
      runId: "current-run",
      sessionId: "current-run-session",
      acquiredAt: "2026-08-17T09:00:00.000Z",
      expiresAt: "2026-08-17T09:30:00.000Z",
    });
    assert.equal(fresh.branch, "agent/issue-583");
    assert.equal(fresh.worktree, ".worktrees/issue-583");
    assert.deepEqual(parseIssueLease(serializeIssueLease(fresh)), fresh);
  });
});

describe("canonical worktree/branch compatibility", () => {
  test("recognizes and reuses an agent/issue-N worktree created by the established naming convention without recreating it", async () => {
    const cwd = mkdtempSync(join(tmpdir(), "coordination-legacy-worktree-"));
    temporaryDirectories.push(cwd);
    git(cwd, ["init", "-q"]);
    git(cwd, ["config", "user.name", "Coordination Compatibility Test"]);
    git(cwd, ["config", "user.email", "coordination-compat@example.invalid"]);
    writeFileSync(join(cwd, ".gitignore"), "/.worktrees/\n");
    execFileSync("sh", ["-c", "printf baseline > baseline.txt && git add baseline.txt .gitignore && git commit -qm baseline"], {
      cwd,
    });

    // Reproduce exactly what another compatible harness would have produced
    // for issue #583: a branch named `agent/issue-583` and a worktree
    // checked out at `.worktrees/issue-583`, using raw git commands rather
    // than calling any coordination code, so this proves the module
    // recognizes pre-existing state rather than only its own freshly
    // created state.
    const legacyPath = join(cwd, ".worktrees", "issue-583");
    git(cwd, ["branch", "agent/issue-583"]);
    execFileSync("git", ["-C", cwd, "worktree", "add", "-q", legacyPath, "agent/issue-583"]);
    writeFileSync(join(legacyPath, "legacy-marker.txt"), "created before this run\n");
    execFileSync("sh", ["-c", "git add legacy-marker.txt && git commit -qm legacy"], { cwd: legacyPath });

    const recognized = await ensureIssueWorktree(cwd, 583);
    assert.equal(recognized, legacyPath);
    assert.equal(git(recognized, ["branch", "--show-current"]), "agent/issue-583");
    assert.equal(git(recognized, ["log", "-1", "--format=%s"]), "legacy");
  });
});
